enum ActionTypes {
	FETCH_ARTICLE = 'FETCH_ARTICLE',
	FETCH_ARTICLE_SUC = 'FETCH_ARTICLE_SUC',
	FETCH_ONE_ARTICLE = 'FETCH_ONE_ARTICLE',
	FETCH_ONE_ARTICLE_SUC = 'FETCH_ONE_ARTICLE_SUC',
	ADD_ARTICLE = 'ADD_ARTICLE',
	DELETE_ARTICLE = 'DELETE_ARTICLE',
}

export default ActionTypes;
